"""Add selling_partner_id to AmazonOAuthTokens

Revision ID: af3f17f3af4d
Revises: f0a4fabb92e8
Create Date: 2025-02-16 20:21:28.121202

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'af3f17f3af4d'
down_revision = 'f0a4fabb92e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('o_auth_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('selling_partner_id', sa.String(length=50), nullable=False),
    sa.Column('access_token', sa.String(length=500), nullable=False),
    sa.Column('refresh_token', sa.String(length=500), nullable=False),
    sa.Column('expires_in', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('selling_partner_id')
    )
    with op.batch_alter_table('amazon_oauth_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selling_partner_id', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('expires_in', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('access_token',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('refresh_token',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['selling_partner_id'])
        batch_op.drop_constraint('amazon_oauth_tokens_seller_id_fkey', type_='foreignkey')
        batch_op.drop_column('expires_at')
        batch_op.drop_column('seller_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('amazon_oauth_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('amazon_oauth_tokens_seller_id_fkey', 'amazon_sellers', ['seller_id'], ['seller_id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('refresh_token',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('access_token',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('expires_in')
        batch_op.drop_column('selling_partner_id')

    op.drop_table('o_auth_token')
    # ### end Alembic commands ###
