"""Initial migration

Revision ID: f0a4fabb92e8
Revises: 
Create Date: 2025-02-15 17:28:44.397168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0a4fabb92e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amazon_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(length=255), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cache_key')
    )
    op.create_table('amazon_sellers',
    sa.Column('seller_id', sa.String(length=50), nullable=False),
    sa.Column('seller_name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('seller_id')
    )
    op.create_table('amazon_oauth_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.String(length=50), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['amazon_sellers.seller_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('amazon_orders',
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('seller_id', sa.String(length=50), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('order_status', sa.String(length=50), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['amazon_sellers.seller_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('amazon_products',
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('seller_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['amazon_sellers.seller_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('amazon_fees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('fee_type', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['amazon_orders.order_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('amazon_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['amazon_orders.order_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['amazon_products.product_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('amazon_refunds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('refund_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['amazon_orders.order_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('amazon_refunds')
    op.drop_table('amazon_order_items')
    op.drop_table('amazon_fees')
    op.drop_table('amazon_products')
    op.drop_table('amazon_orders')
    op.drop_table('amazon_oauth_tokens')
    op.drop_table('amazon_sellers')
    op.drop_table('amazon_cache')
    # ### end Alembic commands ###
